# Generated by Django 3.2.12 on 2022-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("street_line_1", models.CharField(max_length=255)),
                ("street_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("zipcode", models.CharField(max_length=10)),
            ],
        ),
    ]
